#%RAML 1.0
securitySchemes:
  SecurityScheme01:
    type: Pass Through
title: New API accounts
description: blablabla
mediaType:
  - application/json
protocols:
  - HTTP
  - HTTPS
/accounts:
  get:
    displayName: get accounts
    securedBy: []
securedBy: []
types:
  account:
    description: example data type
    example:
      strict: true
      value: {}
    type: object
