#%RAML 1.0
title: Move DY API accounts
version: v1
mediaType:
  - application/json
  
/accounts:
  get:
    displayName: get accounts
    description: "null"
    body: {}
    securedBy: []
types:
  account:
    description: example data type
    properties:
      id?:
        example: CCC
        type: string
      firstName:
        example: Andre Strenger
        type: string
securitySchemes:
  SecurityScheme01:
    type: Pass Through
    describedBy: {}

description: blablabla

protocols:
  - HTTP
  - HTTPS
securedBy: []
