#%RAML 1.0
/accounts:
  get:
    displayName: get accounts
    description: "null"
    body: {}
    securedBy: []
types:
  account:
    description: example data type
    example:
      strict: true
      value: |-
        {
           id: avc,
           firstName: af, 
           lastName: aa, 
           address: aa, postal: aa, country:a, miles :1, creationDate :datetime,  type:p
        }
    properties:
      id?:
        example: Example
        type: string
      firstName:
        example: Example
        type: string
securitySchemes:
  SecurityScheme01:
    type: Pass Through
    describedBy: {}
title: New API accounts
description: blablabla
mediaType:
  - application/json
protocols:
  - HTTP
  - HTTPS
securedBy: []
